id: I19E64FBE
legacy_id: P010686
ocr_import_info:
  bdrc_scan_id: W1PD181182
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T07:08:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:18:55.940237+00:00'
last_modified: 2022-09-01 12:19:02.252334
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD181182
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD181182
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཡག་ཟེ་གཏེར་སྟོན་པདྨ་བསྟན་འཕེལ་གྱི་གཏེར་ཆོས།
  author: གཏེར་སྟོན་པདྨ་བསྟན་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.4825039411264529
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I3PD108:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD108
      total_pages: 172
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3PD108.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.4825039411264529
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
