id: I19E64FBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:09:22+00:00'
last_modified: '2022-06-08T16:48:08.155907+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181182
  title: གཡག་ཟེ་གཏེར་སྟོན་པདྨ་བསྟན་འཕེལ་གྱི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A5D4:
      image_group_id: I3PD108
      title: ''
      total_pages: 172
      order: 1
      base_file: A5D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
